import { access, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

import { createNodeExec } from "../exec.js";
import { buildRunDefaultEnv } from "../run.js";
import type { OttoStateV1 } from "../state.js";
import type { OttoConfig } from "@otto/config";
import type {
  OttoRunner,
  OttoExec,
  OttoExecResult,
  OttoPromptAdapter,
  OttoQualityCheckResult,
} from "@otto/ports";
import { OK_SENTINEL_SPEC, matchOutputSentinel } from "../workflow/sentinels.js";
import {
  ensureMergeSourceBranchExists,
  ensureBaseBranchCheckedOut,
  prepareMergeBackMerge,
} from "./post-run-merge-back-support.js";

type MergeBackStatus =
  | "merged"
  | "skipped"
  | "aborted"
  | "failed";

export interface MergeBackResult {
  status: MergeBackStatus;
  message: string;
}

export async function ensureTemporaryMergeBackEnvFile(args: {
  repoPath: string;
  testEnv: Record<string, string> | undefined;
}): Promise<() => Promise<void>> {
  const testEnv = args.testEnv ?? {};
  const entries = Object.entries(testEnv);
  if (entries.length === 0) {
    return async () => undefined;
  }

  const envTestPath = path.join(args.repoPath, ".env.test");
  try {
    await access(envTestPath);
    return async () => undefined;
  } catch {
    const lines = [
      "# Auto-generated by Otto for post-run merge-back checks",
      ...entries
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([key, value]) => `${key}=${value}`),
      "",
    ];
    await writeFile(envTestPath, lines.join("\n"), "utf8");
    return async () => {
      try {
        await unlink(envTestPath);
      } catch {
        // Best effort cleanup.
      }
    };
  }
}

function getTaskRunner(config: OttoConfig): OttoRunner {
  return config.runners.byRole?.task ?? config.runners.default;
}

function summarizeFirstFailure(
  results: OttoQualityCheckResult[],
): string {
  const failed = results.find((result) => !result.ok);
  if (!failed) {
    return "unknown check failure";
  }
  const detail = (failed.stderr || failed.stdout || "").trim().split("\n")[0] ?? "";
  return detail ? `${failed.name}: ${detail}` : failed.name;
}

function makeExecWithDefaults(state: OttoStateV1): OttoExec {
  const rawExec = createNodeExec();
  const defaultEnv = buildRunDefaultEnv(state);
  return {
    run: async (cmd, options) =>
      await rawExec.run(cmd, {
        ...options,
        env: {
          ...defaultEnv,
          ...(options.env ?? {}),
        },
      }),
  };
}

async function runGit(
  exec: OttoExec,
  cwd: string,
  args: string[],
  timeoutMs = 120_000,
): Promise<OttoExecResult> {
  return await exec.run(["git", ...args], {
    cwd,
    timeoutMs,
    label: `git ${args.join(" ")}`,
  });
}


async function abortPendingMerge(exec: OttoExec, cwd: string): Promise<void> {
  await runGit(exec, cwd, ["merge", "--abort"], 30_000);
}

async function getConflictedFiles(
  exec: OttoExec,
  cwd: string,
): Promise<string[]> {
  const conflicts = await runGit(
    exec,
    cwd,
    ["diff", "--name-only", "--diff-filter=U"],
    30_000,
  );
  if (conflicts.exitCode !== 0 || conflicts.timedOut) {
    return [];
  }
  return conflicts.stdout
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
}

function summarizeRunnerError(result: {
  error?: string;
  outputText?: string;
}): string {
  const source = (result.error || result.outputText || "runner resolution failed").trim();
  const line = source.split(/\r?\n/)[0] ?? "runner resolution failed";
  return line.slice(0, 220);
}

async function attemptConflictResolutionWithRunner(args: {
  prompt: OttoPromptAdapter;
  config: OttoConfig;
  exec: OttoExec;
  repoPath: string;
  baseBranch: string;
  worktreeBranch: string;
}): Promise<{ ok: boolean; message: string }> {
  const conflictedBefore = await getConflictedFiles(args.exec, args.repoPath);
  if (conflictedBefore.length === 0) {
    return {
      ok: false,
      message: "Merge-back failed: merge did not complete and no conflicted files were detected.",
    };
  }

  const shouldResolve = await args.prompt.confirm(
    `Merge conflicts detected in ${conflictedBefore.length} file(s). Attempt automatic conflict resolution now?`,
    { defaultValue: true },
  );
  if (!shouldResolve) {
    return {
      ok: false,
      message: "Merge-back aborted: user declined automatic conflict resolution.",
    };
  }

  const taskRunner = getTaskRunner(args.config);
  const conflictList = conflictedBefore.map((file) => `- ${file}`).join("\n");
  const instructions = [
    "<ROLE>",
    "You are resolving git merge conflicts for a post-run merge-back.",
    "</ROLE>",
    "",
    "<CONTEXT>",
    `- Repository: ${args.repoPath}`,
    `- Merge target: ${args.worktreeBranch} -> ${args.baseBranch}`,
    "- A merge is in progress with unresolved conflicts.",
    "</CONTEXT>",
    "",
    "<CONFLICTED_FILES>",
    conflictList,
    "</CONFLICTED_FILES>",
    "",
    "<REQUIREMENTS>",
    "1. Resolve every merge conflict marker in the listed files.",
    "2. Stage each resolved file with git add.",
    "3. Do NOT run git commit or git merge --continue.",
    "4. Keep changes minimal and deterministic.",
    "5. When all conflicts are resolved and staged, reply with <OK>.",
    "</REQUIREMENTS>",
    "",
  ].join("\n");

  const resolution = await taskRunner.run({
    role: "task",
    phaseName: "post-merge-conflict-resolution",
    prompt: instructions,
    cwd: args.repoPath,
    exec: args.exec,
    timeoutMs: 12 * 60_000,
  });

  if (!resolution.success) {
    return {
      ok: false,
      message: `Merge-back conflict resolution failed: ${summarizeRunnerError(resolution)}`,
    };
  }

  let acknowledged = matchOutputSentinel(
    resolution.outputText,
    OK_SENTINEL_SPEC,
  ).matched;
  if (!acknowledged && resolution.sessionId) {
    const followUp = await taskRunner.run({
      role: "task",
      phaseName: "post-merge-conflict-resolution",
      prompt: "Reply with <OK> only after all merge conflicts are resolved and staged.",
      cwd: args.repoPath,
      exec: args.exec,
      sessionId: resolution.sessionId,
      timeoutMs: 2 * 60_000,
    });
    acknowledged =
      followUp.success &&
      matchOutputSentinel(followUp.outputText, OK_SENTINEL_SPEC).matched;
  }

  const conflictedAfter = await getConflictedFiles(args.exec, args.repoPath);
  if (conflictedAfter.length > 0) {
    return {
      ok: false,
      message: `Merge-back conflict resolution incomplete: ${conflictedAfter.length} conflicted file(s) remain.`,
    };
  }

  if (!acknowledged) {
    return {
      ok: false,
      message:
        "Merge-back conflict resolution failed: runner did not acknowledge completion with <OK>.",
    };
  }

  return {
    ok: true,
    message: "Merge conflicts resolved automatically.",
  };
}

export async function maybeRunPostCleanupMergeBack(args: {
  state: OttoStateV1;
  config: OttoConfig;
  prompt: OttoPromptAdapter;
  exec?: OttoExec;
}): Promise<MergeBackResult> {
  const { state, config, prompt } = args;
  const exec = args.exec ?? makeExecWithDefaults(state);

  const proceed = await prompt.confirm(
    `Merge ${state.worktree.branchName} into ${state.worktree.baseBranch} now?`,
    { defaultValue: true },
  );
  if (!proceed) {
    return {
      status: "skipped",
      message: "Skipped merge-back at user request.",
    };
  }

  const repoPath = state.mainRepoPath;
  const baseBranch = state.worktree.baseBranch;
  const worktreeBranch = state.worktree.branchName;

  const branchCheck = await ensureMergeSourceBranchExists({
    exec,
    repoPath,
    worktreeBranch,
  });
  if (branchCheck) {
    return branchCheck;
  }

  const mergePreparation = await prepareMergeBackMerge({
    prompt,
    config,
    exec,
    repoPath,
    baseBranch,
    worktreeBranch,
    abortPendingMerge,
    attemptConflictResolution: attemptConflictResolutionWithRunner,
  });
  if (mergePreparation.earlyResult) {
    return mergePreparation.earlyResult;
  }

  const removeTempEnvFile = await ensureTemporaryMergeBackEnvFile({
    repoPath,
    testEnv: state.testEnv,
  });
  const quality = config.quality;
  try {
    if (quality) {
      const qualityResult = await quality.adapter.runChecks({
        worktreePath: repoPath,
        exec,
        checks: quality.checks,
      });
      if (!qualityResult.ok) {
        await abortPendingMerge(exec, repoPath);
        return {
          status: "failed",
          message: `Merge-back validation failed (quality): ${summarizeFirstFailure(qualityResult.results)}`,
        };
      }
    }

    const integration = config.integration;
    if (integration?.checks.length) {
      const integrationAdapter = integration.adapter ?? quality?.adapter;
      if (!integrationAdapter) {
        await abortPendingMerge(exec, repoPath);
        return {
          status: "failed",
          message:
            "Merge-back validation failed: integration checks are configured but no adapter is available.",
        };
      }

      const integrationResult = await integrationAdapter.runChecks({
        worktreePath: repoPath,
        exec,
        checks: integration.checks,
      });
      if (!integrationResult.ok) {
        await abortPendingMerge(exec, repoPath);
        return {
          status: "failed",
          message: `Merge-back validation failed (integration): ${summarizeFirstFailure(integrationResult.results)}`,
        };
      }
    }
  } finally {
    await removeTempEnvFile();
  }

  const commit = await runGit(exec, repoPath, [
    "commit",
    "-m",
    `Merge ${worktreeBranch} after Otto run ${state.runId}`,
  ], 60_000);
  if (commit.exitCode !== 0 || commit.timedOut) {
    await abortPendingMerge(exec, repoPath);
    const commitMessage = (commit.stderr || commit.stdout || "git commit failed").trim();
    return {
      status: "failed",
      message: `Merge-back failed while committing merge: ${commitMessage}`,
    };
  }

  return {
    status: "merged",
    message: `Merged ${worktreeBranch} into ${baseBranch} with post-merge validations.`,
  };
}
